# Generated by Django 5.2.4 on 2025-08-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_en',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_es',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_ru',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_uk',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sender Name'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Sender Name'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sender Name'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Sender Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='project_description_en',
            field=models.TextField(null=True, verbose_name='Order Description'),
        ),
        migrations.AddField(
            model_name='order',
            name='project_description_es',
            field=models.TextField(null=True, verbose_name='Order Description'),
        ),
        migrations.AddField(
            model_name='order',
            name='project_description_ru',
            field=models.TextField(null=True, verbose_name='Order Description'),
        ),
        migrations.AddField(
            model_name='order',
            name='project_description_uk',
            field=models.TextField(null=True, verbose_name='Order Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Project Title'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Project Title'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Project Title'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Project Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Service Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Service Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Service Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Service Title'),
        ),
    ]
